food = input("Enter a food item: ")
print()
car = input("Whats your favroite car? ")
print()
place = input("Whats the name of a restarant: ")
print()
date2 = input("Whats the date? ")
print()
name = input("Whats your Name? ")
print()
vac = input("Where do you want to go on vacation?")
print()

print(f"Hi my name is {name}, and I was driving my {car} on the date {date2} to get my favorite food {food} the place is {place}, and Im so glad I got {food} because im going on vacation to {vac}")